"""update models

Revision ID: 9b54e94f873b
Revises: 8f3c14b02f00
Create Date: 2025-05-30 15:01:34.792623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b54e94f873b'
down_revision = '8f3c14b02f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('birth_day',
               existing_type=sa.DATE(),
               type_=sa.String(length=70),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('birth_day',
               existing_type=sa.String(length=70),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
