"""update models

Revision ID: c082ceb5c7bb
Revises: 9b54e94f873b
Create Date: 2025-05-30 15:20:23.797461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c082ceb5c7bb'
down_revision = '9b54e94f873b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_day', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('number_lesson', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('class_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lesson_subject_id', 'subject', ['subject_id'], ['id'])
        batch_op.create_foreign_key('fk_lesson_class_group_id', 'class_group', ['class_group_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('hours_per_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_per_week', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_lesson_subject_id', type_='foreignkey')
        batch_op.drop_constraint('fk_lesson_class_group_id', type_='foreignkey')
        batch_op.drop_column('class_group_id')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('number_lesson')
        batch_op.drop_column('week_day')

    # ### end Alembic commands ###
